api-addr: :2633
bootnode: "/ip4/112.35.181.215/tcp/1634/p2p/16Uiu2HAmE2CijKqdmmHLczfv9WmD73SVza4nnwd9e6upskUhBshJ"
bootnode-mode: true
clef-signer-enable: false
clef-signer-endpoint: ""
clef-signer-ethereum-address: ""
config: ""
cors-allowed-origins: ["*"]
data-dir: metaengineData
db-block-cache-capacity: "33554432"
db-capacity: "5000000"
db-disable-seeks-compaction: false
db-open-files-limit: "200"
db-write-buffer-size: "33554432"
debug-api-addr: :2635
debug-api-enable: true
gateway-mode: true
global-pinning-enable: true
help: false
nat-addr: "112.35.181.215:1634"
network-id: "16666"
p2p-addr: :2634
p2p-quic-enable: true
p2p-ws-enable: true
password: "123456"
password-file: ""
payment-early: "1000000000000"
payment-threshold: "10000000000000"
payment-tolerance: "50000000000000"
resolver-options: []
standalone: false
swap-enable: true
swap-endpoint: http://112.35.181.215:8545
swap-factory-address: "0x28A016c7ff9095d08E22a323Bc885D3C6cF81b02"
swap-initial-deposit: "0"
tracing-enable: false
tracing-endpoint: 127.0.0.1:6831
tracing-service-name: fish
verbosity: info
welcome-message: ""
